apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: demo
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Never
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo1
  ---
apiVersion: v1
kind: Namespace
metadata:
  name: demo2
